---
title: "544_project2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(acs)
library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(maptools)
library(rgdal)
library(tidyr)
library(RColorBrewer)
library("spdep")
library(plyr)
library(tmap)
library(SpatialEpi)
library(RColorBrewer)
library(ggplot2)
library(ggridges)
library(INLA)
library(maps)
library(shapefiles)
library(maptools)
library(dplyr)
library(sp)
library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
```

```{r}
#nyc_tracts <- county_subdivisions(state = '36', county = c('061','047','081','005','085'))
nyc_tracts <- tracts(state = '36', county = c('061','047','081','005','085'))

summary(nyc_tracts)
str(nyc_tracts)
plot(nyc_tracts)

```

```{r}
#NYPD <- rgdal::readOGR(dsn = "." , layer = "geo_export_b15ad1ee-6f4f-498f-8293-dd279825379d")
NYPD_complain <- rgdal::readOGR(dsn = "." , layer = "geo_export_af75edd8-edf3-4940-8fd1-b91d42e44702")

#crime = read.csv("../input/Crime_Data_2010_2017.csv")

#NYcrime <- NYPD@data
NYcrime <- NYPD_complain@data
head(NYcrime)
table(NYcrime$date_cmpln)
NYcrime$time.label<- unlist(lapply(NYcrime$date_cmpln, grepl, pattern = "2019*"))
table(NYcrime$time.label)
NYcrime.2019 <- NYcrime %>% filter(time.label == TRUE)
head(NYcrime.2019)
dim(NYcrime.2019)
```

```{r}
#census_api_key("3983d9105bd19394f8d12c53de7fcbb56bd0e706", install = TRUE)
readRenviron("~/.Renviron")
dt1 <- get_acs(geography = "tract",  state = "NY", variables = c(population = "B01003_001"), year = 2019)
head(dt1)
###"county subdivision"
nyc_pop <- sp::merge(x = nyc_tracts, y = dt1, by = "GEOID", all.x = TRUE)

data(crime)
head(crime)
str(crime)

register_google(key = "AIzaSyDzVJFVyBVkdE2tuaVhZq5X0NnwtXvL1wg")
#r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
#nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)
#summary(nyc_neighborhoods)
#nyc_neighborhoods_df <- tidy(nyc_neighborhoods)

nyc <- get_map(location = c(lon = -74.00, lat = 40.71), maptype = "terrain", zoom = 11)
ggmap(nyc) + 
  geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="blue", fill=NA) + stat_density2d(aes(x = longitude, y = latitude, fill = ..level..,alpha=..level..), bins = 20, geom = "polygon", data = NYcrime.2019) +
  scale_fill_gradient(high = "red")+
  ggtitle("Map of Crime Density in NYC")

ggmap(nyc)+ geom_point(aes(x = longitude, y = latitude, colour = "red"), data = NYcrime.2019, alpha = 0.1)

```
```{r}
nyc_pop %>% filter(estimate == 0)
```


```{r}
colnames(NYcrime.2019)
points.frame <- as.data.frame(NYcrime.2019[,c("longitude", "latitude")])
points.frame <- SpatialPoints(points.frame)
spd <- sf::as_Spatial(st_geometry(nyc_tracts), IDs = as.character(nyc_tracts$GEOID))
proj4string(spd)
proj4string(points.frame) <- proj4string(spd) 
admin2.key <- over(points.frame, spd)
summary(admin2.key)
NYcrime.2019$GEOID <- nyc_tracts$GEOID[admin2.key]
```
```{r}
library(table1)
NYcrime.2019.subset<- NYcrime.2019 %>% filter(GEOID %in% nyc_popc$GEOID)
dim(NYcrime.2019.subset)
colnames(NYcrime.2019.subset)
table(NYcrime.2019.subset$law_cat_cd)
nyc_b <- table1(~law_cat_cd + boro_nm+ susp_age_g + susp_race + susp_sex + vic_age_gr + vic_race + vic_sex,data=as.data.frame(NYcrime.2019.subset))


nyc_b
```

```{r}
crime.sp = SpatialPoints(NYcrime[, c("longitude","latitude")])
all_crime <- NYcrime.2019 %>% group_by(GEOID) %>% dplyr::summarise(num_points = n())
all_crime
nyc_popc <- sp::merge(x = nyc_pop, y = all_crime, by = "GEOID", all.x = TRUE)
nyc_popc <- nyc_popc %>% filter(estimate > 0)


nyc_popc[is.na(nyc_popc$num_points),"num_points"] <- 0
nyc_popc <- nyc_popc %>% filter(estimate >= num_points)
summary(nyc_popc$num_points)
#nyc_popc <- nyc_popc %>% filter(estimate != 0)
Y <- nyc_popc$num_points
E <-  nyc_popc$estimate * sum(nyc_popc$num_points)/sum(nyc_popc$estimate)
nyc_popc$SMR <- Y/E
nyc_popc$EXP <- E
nyc_popc%>% filter(nyc_popc$SMR > 100)
#nyctest <- nyc_popc %>% filter(estimate >= num_points)

#table(is.na(nyc_popc1$num_points))
dim(nyc_popc)
summary(exp(nyc_popc$SMR))
hist(nyc_popc$SMR)
pal1 <- brewer.pal(9,"OrRd")
plot(nyc_popc["SMR"])
#plot(nyc_popc["SMR"], add = TRUE, breaks = seq(0,10,1))

# 
# plot(nyc_popc["SMR"], 
#      main = "NYC_crime", 
#      breaks = c(0, 0.3, 0.8, 1.5, 10)) 
#   scale_fill_gradient(low = "yellow", high = "red", limits=c(0,500))
# summary(nyc_popc$SMR)
summary(nyc_popc$SMR)

library(RColorBrewer)
pal <- brewer.pal(5, "OrRd")
nyc_popc$SMR_INT <-cut(nyc_popc$SMR, breaks =c(-0.0001, 0.3, 0.8, 1.5, 5, 100), labels =c("<0.3","0.3-0.8","0.8-1.5", "1.5-5", ">5"))

plot(nyc_popc["SMR_INT"], pal = pal, key.pos = 1)


####delete those polygon in geometry

```

```{r}
library(INLA)
head(nyc_popc)
m0 <- inla(num_points ~ f(GEOID, model = "iid"),family = "poisson", E = EXP, data = as.data.frame(nyc_popc), control.predictor = list(compute = TRUE))
head(m0$summary.fitted.values)
nyc_popc$RRpmean0<- m0$summary.fitted.values[, 1]
summary(nyc_popc["RRpmean0"])

plot(nyc_popc["RRpmean0"],breaks = seq(0,10,0.5))
nyc_popc$RRpmean0_INT <-cut(nyc_popc$RRpmean0, breaks =c(-0.0001, 0.5, 0.8, 1.2, 5, 100), labels =c("<0.5","0.5-0.8","0.8-1.2", "1.2-5", ">5"))
plot(nyc_popc["RRpmean0_INT"], pal = pal, key.pos = 1)


nyc_popc %>% filter(RRpmean0 > 10)
# length(nyc_popc[nyc_popc$RRpmean0 >10,])
# 
# plot(nyc_popc["SMR"], 
#      main = "Philadelphia homicide density per square km", 
#      breaks = c(0, 0.3, 0.8, 1.5, 10)) 
#   scale_fill_gradient(low = "blue", high = "red", limits=c(20,80))
# summary(nyc_popc$SMR)
# nyc_popc$SMR_INT <-cut(nyc_popc$SMR, breaks =c(-0.0001, 0.3, 0.8, 1.5, 10, 100, 500), labels =c("<0.3","0.3-0.8","0.8-1.5", "1.5-10", "10-100", ">100"))
# 
# plot(nyc_popc["SMR_INT"], pal = pal)

###another way

# sa_fb %>%
#   mutate(rate_cut = cut_interval(rate, n = 6)) %>%
#   ggplot() +
#   geom_sf(aes(fill = rate_cut))
# 
# 
# usa_fb %>%
#   mutate(rate_cut = cut_number(rate, n = 6)) %>%
#   ggplot() +
#   geom_sf(aes(fill = rate_cut))
```

```{r}
#inla(num_points ~ f(GEOID, model = "iid"),family = "poisson", E = EXP, data = nyc_popc, control.predictor = list(compute = TRUE))
#nyc.adj <- poly2nb(nyc_popc)

#B.nyc <- nb2mat(nyc.adj, style = "B", zero.policy = TRUE) 
#W.nyc <- nb2mat(nyc.adj, style = "W", zero.policy = TRUE)

#col.W <- nb2listw(nyc.adj, style = "W", zero.policy = TRUE) 
#col.B <- nb2listw(nyc.adj, style = "B", zero.policy = TRUE)
nyc_popc$GEOID2 <- as.numeric(nyc_popc$GEOID)
nyc_popc$id1 <- 1: length(nyc_popc$GEOID)
nyc_popc$id2 <- 1: length(nyc_popc$GEOID)

#nc.sids2$RRpmean1 <- m1$summary.fitted.values[, 1]
```
Besag
```{r}
dim(nyc_popc)
m1 <- inla(num_points ~ 1 + f(id1, model = "iid")+ f(id2, model = "besag", graph = W.nyc) , family = "poisson",E = EXP, data = as.data.frame(nyc_popc),control.predictor = list(compute = TRUE))
# Define summary quantities of interest as with iid # model
summary(m1)

nareas <- 2124
mat.marg <- matrix(NA,nrow=nareas,ncol=1000)
m <- m1$marginals.random$id2
for (i in 1:nareas){
  Sre <- m[[i]]
  mat.marg[i,] <- inla.rmarginal(1000,Sre)
}
var.Sre <- apply(mat.marg,2,var)
var.eps <- inla.rmarginal(1000,inla.tmarginal(function(x) 1/x,m1$marginals.hyper$"Precision for id1"))
mean(var.Sre)
mean(var.eps)
perc.var.Sre <- mean(var.Sre/(var.Sre+var.eps))
perc.var.Sre
```

Bym2
```{r}
formula <- num_points ~ 1 + f(id1, model="bym2", graph=W.nyc)
dim(W.nyc)

m2 <- inla(formula, data=as.data.frame(nyc_popc), family="poisson",E=EXP, control.predictor=list(compute=TRUE),control.compute=list(config = TRUE))
```
```{r}
m2$fit2fitted <- m2$summary.fitted.values$`0.5quant`
m2$summary.hyperpar[,1:5]
plot(nyc_popc["RRpmean0"], breaks = seq(0,20,2), key.pos = 1)
```

```{r}
dim(nyc_popc)
nyc_popc$RRpmean1<- m2$summary.fitted.values[, 1]
summary(nyc_popc["RRpmean1"])

plot(nyc_popc["RRpmean1"])
plot(nyc_popc["RRpmean1"],breaks = seq(0,28,2), key.pos = 1)
nyc_popc$RRpmean1_INT <-cut(nyc_popc$RRpmean1, breaks =c(-0.0001, 0.5, 0.8, 1.2, 5, 100), labels =c("<0.5","0.5-0.8","0.8-1.2", "1.2-5", ">5"))
plot(nyc_popc["RRpmean1_INT"], pal = pal, key.pos = 1)


summary(m1$summary.fitted.values[, 4])
nyc_popc$RR0_bin <- m0$summary.fitted.values[, 4] > 1.5
nyc_popc$RR1_bin <- m2$summary.fitted.values[, 4] > 1.5
table(nyc_popc$RR0_bin)
table(nyc_popc$RR1_bin)

plot(nyc_popc["RR0_bin"])


```

```{r}
plot(nyc_popc["RR1_bin"])
```


```{r}
m2$fit2fitted <- m2$summary.fitted.values$`0.5quant`
m2$summary.hyperpar[,1:5]
```
The posterior median for the proportion of the residual variation that is spatial is 0.96


```{r}
quasipmod <- glm(num_points ~ 1, offset = log(EXP), data = nyc_popc,family = quasipoisson())
sidsres <- residuals(quasipmod, type = "pearson")
hist(sidsres)
nyc_popc %>% filter(res > 30)
nyc_popc <- nyc_popc %>% filter(res <= 30)
nyc_popc %>% filter(estimate < 200)

nyc.adj <- poly2nb(nyc_popc)

B.nyc <- nb2mat(nyc.adj, style = "B", zero.policy = TRUE) 
W.nyc <- nb2mat(nyc.adj, style = "W", zero.policy = TRUE)

col.W <- nb2listw(nyc.adj, style = "W", zero.policy = TRUE) 
col.B <- nb2listw(nyc.adj, style = "B", zero.policy = TRUE)
nyc_popc$GEOID2 <- as.numeric(nyc_popc$GEOID)



moran.test(nyc_popc$res, col.W, zero.policy= TRUE)
```
This analysis suggests significant clustering.

```{r}
nyc_popc$res <- sidsres
summary(sidsres)
par(mar = c(0.1, 0.1, 0.1, 0.1))
plot(nyc_popc["res"], breaks = seq(-4,20,0.5))
plot(nyc_popc["res"])
```

```{r}
moran.test(nyc_popc$res, col.W, zero.policy= TRUE)
```
```{r}
moran.test(nyc_popc$res, col.B, zero.policy= TRUE)
```

```{r}
geary.test(nyc_popc$res, col.W, zero.policy= TRUE)
```
```{r}
geary.test(nyc_popc$res, col.B, zero.policy= TRUE)
```

remember to change the variable name
```{r}
#local <- localmoran(x = nyc_popc$Freq, listw = nb2listw(neighbours2, style = "W"))
local <- localmoran(x = nyc_popc$num_points, listw = col.W, zero.policy = TRUE)
local
quadrant <- vector(mode="numeric",length=nrow(local))

# centers the variable of interest around its mean
m.crime <- nyc_popc$num_points - mean(nyc_popc$num_points)     

# centers the local Moran's around the mean
m.local <- local[,1] - mean(local[,1])    

# significance threshold
signif <- 0.1 

# builds a data quadrant
quadrant[m.crime >0 & m.local>0] <- 4  
quadrant[m.crime <0 & m.local<0] <- 1      
quadrant[m.crime <0 & m.local>0] <- 2
quadrant[m.crime >0 & m.local<0] <- 3
quadrant[local[,5]>signif] <- 0   

brks <- c(0,1,2,3,4)
colors <- c("white","blue",rgb(0,0,1,alpha=0.4),rgb(1,0,0,alpha=0.4),"red")
#brksfindInterval(nyc_popc$SMR, brks)
#plot(nyc_popc$geometry)
plot(nyc_popc$geometry,border="black",col=colors[findInterval(quadrant,brks,all.inside=FALSE)],main = "LISA cluster map")
legend(x = -73.65, y = 40.65,legend=c("insignificant","low-low","low-high","high-low","high-high"),
       fill=colors,bty="n")
```

```{r}
population <- nyc_popc$estimate
cases <- nyc_popc$num_points
n <- length(cases)
centroids <- matrix(0, nrow = n, ncol = 2)

for (i in 1:n) {
centroids[i, ] <- c(nyc_popc$INTPTLON[i], nyc_popc$INTPTLAT[i]) }
geo <- centroids
```

```{r}
pop.upper.bound <- 0.4
n.simulations <- 999
alpha.level <- 0.05
Kpoisson <- kulldorff(geo, cases, population, expected.cases = nyc_popc$Exp, pop.upper.bound, n.simulations, alpha.level, plot = T) 
Kpoisson
Kcluster0 <- Kpoisson$most.likely.cluster$location.IDs.included
Kcluster1 <-Kpoisson$secondary.clusters[[16]]$location.IDs.included
Kcluster2 <-Kpoisson$secondary.clusters[[18]]$location.IDs.included
Kcluster3 <-Kpoisson$secondary.clusters[[27]]$location.IDs.included 
Kcluster4 <-Kpoisson$secondary.clusters[[28]]$location.IDs.included 
#$secondary.clusters[[30]] 29 8 10 18
#$secondary.clusters[[30]]$location.IDs.included
#[1] 1656 1650 1645
#Kcluster2 <-Kpoisson$secondary.clusters[[3]]$location.IDs.included
nyc.new <- nyc_popc$geometry
plot(nyc.new, main = "Satscan cluster map")
plot(nyc.new[Kcluster0], add = TRUE, col = "red") 
plot(nyc.new[Kcluster1], add = TRUE, col = "blue") 
plot(nyc.new[Kcluster2], add = TRUE, col = "green")
plot(nyc.new[Kcluster3], add = TRUE, col = "orange") 
plot(nyc.new[Kcluster4], add = TRUE, col = "yellow") 
colors <- c("red","blue","green","orange","yellow")
legend(x = -73.65, y = 40.65,legend=c("Most likely cluster","Secondary likely cluster","Secondary likely cluster","Secondary likely cluster","Secondary likely cluster"),fill=colors,bty="n")
```

